version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    sysctls:
        - net.core.somaxconn=511
  discord:
    build: 
      context: ./services/discord
    env_file: 
      ./services/discord/.env.dev
    volumes:
      - ./services/discord:/home/node/twitch-bot
    command: npm run start:dev
    depends_on:
      - redis
