version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    sysctls:
        - net.core.somaxconn=511
  postgres:
    image: postgres:13-alpine
    env_file: services/postgres/db.env
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  discord:
    build: 
      context: ./services/discord
    env_file: 
      ./services/discord/.env.dev
    volumes:
      - ./services/discord:/home/node/twitch-bot
    command: npm run start:dev
    depends_on:
      - redis
      - postgres
