version: '3.7'

services:
  discord:
    build: 
      context: ./services/discord
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/discord:/usr/local/src/twitch-bot
      - /usr/local/src/twitch-bot/node_modules