name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm ci
      run: npm ci
      working-directory: services/discord 	
    - name: lint
      run: npm run lint
      working-directory: services/discord 	
    - name: test
      run: npm test
      working-directory: services/discord
