name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # This step checks out a copy of your repository.
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: ESLint
      run: |
        npm install
        npm run lint
      working-directory: services/discord